paths:
  pdf_file: "../data/pdf/Herbal_Medicine_for_Modern_Life_-_Ruth_Blanding.pdf"
  data_dir: "../data"
  models_dir: "../models"
  logs_dir: "../logs"
  train_file: "../data/train.txt"
  valid_file: "../data/valid.txt"

training:
  num_train_epochs: 5
  per_device_train_batch_size: 2
  gradient_accumulation_steps: 4
  save_steps: 500
  save_total_limit: 2
  logging_steps: 10
  learning_rate: 5e-5
  fp16: true